Add tests and Github actions
canonical/ght pull request #164
Opened 2022-10-12 16:14 UTC by Dampolo03

2022-10-12 18:59 UTC, anthonydillon requested changes
One small comment is the code

2022-10-12 18:59 UTC, anthonydillon commented on src/test-greenhouse.ts
> +            addPosts(spinner, false, JOB_POST_ID, ["apac", "americas"], page)
Could you test all the regions here to ensure they all work going forward?

2022-10-12 19:01 UTC, anthonydillon commented
Can you ensure you add an issue for assign tests and interactive tests please.

2022-10-13 08:44 UTC, Dampolo03 commented
> Can you ensure you add an issue for assign tests and interactive tests please.

@anthonydillon Done.

2022-12-07 10:47 UTC, anthonydillon commented
@Dampolo03 I am getting the following error now:
```
Failed to get some information from Greenhouse: Error: Cannot find name of the job with 1753300 ID in the https://canonical.greenhouse.io/plans/1753300 page.
```

2022-12-08 10:26 UTC, Dampolo03 commented
> @Dampolo03 I am getting the following error now:
> 
> ```
> Failed to get some information from Greenhouse: Error: Cannot find name of the job with 1753300 ID in the https://canonical.greenhouse.io/plans/1753300 page.
> ```

@anthonydillon Okay, I'll try to look into this. Weirdly, it works for me.

2022-12-14 10:11 UTC, anthonydillon commented
I just don't have permission to see this role. Let's merge and see if the action works.

2022-12-14 10:12 UTC, merged